FROM nginx:1.15.11-alpine

LABEL description="Nextcloud nginx web server" \
      maintainer="SysAlpine <mail@sysalpine.com>"

ENV BACKEND_HOST=127.0.0.1 \
    BACKEND_PORT=9000

RUN apk add --no-cache curl

COPY nginx.conf /etc/nginx/nginx.conf
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

